name: run tests

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '**/README.md'
      - '**/LICENSE'
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Image Artifact
      if: '!cancelled()'
      uses: actions/upload-artifact@v4
      with:
        name: image-artifact
        path: '**/ActualP3V1.png'
